apiVersion: v1
kind: Service
metadata:
  name: lobby-db-service
  labels:
    app: lobby-db
spec:
  selector:
    app: lobby-db
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
      protocol: TCP
  type: ClusterIP
