apiVersion: v1
kind: Service
metadata:
  name: lobby-service
  labels:
    app: lobby-proxy
spec:
  selector:
    app: lobby-proxy
  ports:
    - port: 25565
      targetPort: 25565
      name: mc
      protocol: TCP
  type: ClusterIP
