apiVersion: v1
kind: Service
metadata:
  name: network-service
  labels:
    app: entry-proxy
spec:
  selector:
    app: entry-proxy
  ports:
    - port: 25565
      targetPort: 30065
      name: mc
      protocol: TCP
  type: NodePort
